"""
Module to run tests on SensFunc and FluxCalibrate classes
Requires files in Development suite (REDUX_OUT) and an Environmental variable
"""
import os

import pytest

from IPython import embed

import numpy as np

from pypeit import sensfunc
from pypeit import specobjs
from pypeit.scripts import loader
from pypeit.spectrographs.util import load_spectrograph
from pypeit.tests.tstutils import data_output_path


@pytest.fixture
def kast_blue_files(redux_out):
    std_file = os.path.join(redux_out,
                            'shane_kast_blue', 
                            '600_4310_d55', 
                            'shane_kast_blue_A', 'Science',
                            'spec1d_b24-Feige66_KASTb_20150520T041246.960.fits')
    sci_file = os.path.join(redux_out,
                            'shane_kast_blue', 
                            '600_4310_d55', 
                            'shane_kast_blue_A', 'Science',
                            'spec1d_b27-J1217p3905_KASTb_20150520T045733.560.fits')
    return [std_file, sci_file]


def test_find_std(kast_blue_files):
    # Files
    std_file, sci_file = kast_blue_files
    # Read the specobjs
    sobj = specobjs.SpecObjs.from_fitsfile(std_file)
    # Find the name of the standard-star extraction
    std_names = sobj.identify_standard()
    # There should be only one.
    assert len(std_names) == 1, 'Should only identify one spectrum associated with the standard'
    # Make sure the index conversion works
    std_indx = np.where(sobj.name_indices(std_names[0]))[0]
    assert len(std_indx) == 1, \
        'Somehow found more than one index associated with the standard spectrum name'
    # Get the median S/N of the boxcar extraction and check its value
    med_snr = np.median(sobj[std_indx].BOX_COUNTS * np.sqrt(sobj[std_indx].BOX_COUNTS_IVAR))
    assert med_snr > 100., 'Median S/N is expected to be larger than 100.'


def test_load_std(kast_blue_files):
    # Files
    std_file, sci_file = kast_blue_files
    # Try default loading 
    spec, splice_multi_det = loader.load_standard(std_file)
    assert len(spec) == 1, 'Should only find one spectrum'
    assert not splice_multi_det, 'This spectrum should not be spliced across multiple detectors'

    # Are the names consistent?
    sobj = specobjs.SpecObjs.from_fitsfile(std_file)
    std_names = sobj.identify_standard()
    assert len(std_names) == 1, 'Should only find one source name'
    assert std_names[0] == spec[0].meta['NAME'], \
        'loader.load_standard and SpecObjs.identify_standard found different source names'

    # Try loading when the name is known
    _spec, splice_multi_det = loader.load_standard(std_file, names=std_names[0])
    assert len(_spec) == 1, 'Should only find one spectrum'
    assert not splice_multi_det, 'This spectrum should not be spliced across multiple detectors'
    assert _spec[0].meta['NAME'] == std_names[0], 'Spectrum does not have the correct name'


def test_tweak_std(kast_blue_files):
    # Files
    std_file, sci_file = kast_blue_files
    # Try default loading 
    std_spec, splice_multi_det = loader.load_standard(std_file)

    # Test tweaking
    spec = load_spectrograph(std_spec[0].meta['PYP_SPEC'])
    # This should just return a copy of the input
    twk_spec = spec.tweak_standard(std_spec)
    assert len(twk_spec) == len(std_spec), 'Should return the same number of spectra'
    assert not twk_spec[0] is std_spec[0], 'Object should be a copy'
    assert np.array_equal(twk_spec[0].wave, std_spec[0].wave), 'Wavelengths should be identical'
    assert np.array_equal(twk_spec[0].flux, std_spec[0].flux), 'Flux should be identical'

    # Test masking the first and last 10 pixels
    twk_spec = spec.tweak_standard(std_spec, trim_std_pixs=(10,-10))
    assert np.sum(twk_spec[0].gpm[:10]) == 0, 'Did not mask the first ten pixels.'
    assert np.sum(twk_spec[0].gpm[-10:]) == 0, 'Did not mask the last ten pixels.'


# TODO: Add some tweak tests for spectrographs that have dispname-specific
# behavior


def test_sensfunc(kast_blue_files, redux_out):

    sens_file = data_output_path('sensfunc.fits')
    kast_blue_out = os.path.join(redux_out, 'shane_kast_blue', '600_4310_d55', 'shane_kast_blue_A')

    # Test the meta_spec data of the SensFunc
    spectrograph = load_spectrograph('shane_kast_blue')
    par = spectrograph.default_pypeit_par()
    std_file, sci_file = kast_blue_files
    # Instantiate
    sensFunc = sensfunc.UVISSensFunc([std_file], sens_file, par['sensfunc'])
    # Test the standard loaded
    assert sensFunc.meta_spec['BINNING'] == '1,1'
    assert sensFunc.meta_spec['TARGET'] == 'Feige 66'

    # Vet the sensitivity function generated by the devsuite.

    # Load
    sensFunc = sensfunc.SensFunc.from_file(
        os.path.join(kast_blue_out, 'sens_b24-Feige66_KASTb_20150520T041246.960.fits')
    )

    # Validate some sens table columns
    sens_colnames = ['SENS_ZEROPOINT', 'SENS_ZEROPOINT_FIT', 'SENS_ZEROPOINT_FIT_GPM', 'SENS_WAVE']
    for col in sens_colnames:
        assert col in sensFunc.sens.keys(), f'Missing column "{col}".'

    # Validate the SensFunc attributes
    assert os.path.basename(sensFunc.std_cal) == 'feige66_002.fits.gz'
    assert len(sensFunc.wave) > 0
    assert len(sensFunc.zeropoint) > 0
    assert np.all(np.isfinite(sensFunc.wave))
    assert np.all(np.isfinite(sensFunc.zeropoint))
    assert not np.any(sensFunc.wave < 0)

def test_flux(kast_blue_files):

    # Validate fluxing information
    sobjs = specobjs.SpecObjs.from_fitsfile(kast_blue_files[1])
    sobj = sobjs[0]
    assert 'OPT_FLAM' in sobj.keys(), f'OPT_FLAM missing from {kast_blue_files[1]}'
    assert sobj.OPT_FLAM is not None, f'OPT_FLAM from {kast_blue_files[1]} is None'
    assert len(sobj.OPT_FLAM) > 0, f'OPT_FLAM from {kast_blue_files[1]} is empty'
    assert np.all(np.isfinite(sobj.OPT_FLAM)), f'OPT_FLAM from {kast_blue_files[1]} has infinite or NaN values'
    assert 'WAVE_RMS' in sobj.keys(), f'WAVE_RMS missing from {kast_blue_files[1]}'
    assert sobj.WAVE_RMS is not None, f'WAVE_RMS from {kast_blue_files[1]} is None'
    assert sobj.WAVE_RMS < 0.08 , f'WAVE_RMS from {kast_blue_files[1]} above threshold'
